IndividualTaxCalculator/IndividualTaxCalculator.Web/Models/TaxCalculationRequestViewModel.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IndividualTaxCalculator.Web.Models;

public class TaxCalculationRequestViewModel
{
    [DisplayName("Annual Income")] public decimal AnnualIncome { get; set; }
   
    [DisplayName("Postal Code")] public string PostalCode { get; set; } = "";

    // TODO: Populate postal codes from possible choices in DB
    public IEnumerable<SelectListItem> PostalCodes => new List<SelectListItem>
    {
        new() { Value = "7441", Text = "7441" },
        new() { Value = "A100", Text = "A100" },
        new() { Value = "7000", Text = "7000" },
        new() { Value = "1000", Text = "1000" },
    };
}

IndividualTaxCalculator/IndividualTaxCalculator.Web/Models/TaxCalculationResultViewModel.cs
using System.ComponentModel;

namespace IndividualTaxCalculator.Web.Models;

public class TaxCalculationResultViewModel
{
    [DisplayName("Annual Income")] public decimal AnnualIncome { get; set; }

    [DisplayName("Postal Code")] public string PostalCode { get; set; } = "";

    [DisplayName("Calculated Tax Amount")] public decimal TaxAmount { get; set; }
}

IndividualTaxCalculator/IndividualTaxCalculator.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace IndividualTaxCalculator.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
}

IndividualTaxCalculator/IndividualTaxCalculator.Web/Controllers/TaxCalculationController.cs
using IndividualTaxCalculator.Application.Dtos;
using IndividualTaxCalculator.Application.Interfaces;
using IndividualTaxCalculator.Domain.ValueObjects;
using IndividualTaxCalculator.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace IndividualTaxCalculator.Web.Controllers;

public class TaxCalculationController : Controller
{
    private readonly ITaxCalculationService _taxCalculationService;

    public TaxCalculationController(ITaxCalculationService taxCalculationService)
    {
        _taxCalculationService =
            taxCalculationService ?? throw new ArgumentNullException(nameof(taxCalculationService));
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View(new TaxCalculationRequestViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> Index(TaxCalculationRequestViewModel viewModel)
    {
        var requestDto = new TaxCalculationRequestDto(viewModel.PostalCode, viewModel.AnnualIncome);
        var taxCalculationResultDto = await _taxCalculationService.CalculateTaxForIndividual(requestDto);
        
        return RedirectToAction("Result", taxCalculationResultDto);
    }

    // TODO: Only pass through calculation id and refetch from DB
    public IActionResult Result(TaxCalculationResultDto taxCalculationResultDto)
    {
        var (annualIncome, postalCode, taxAmount) = taxCalculationResultDto;

        return View(new TaxCalculationResultViewModel
        {
            AnnualIncome = annualIncome,
            PostalCode = postalCode,
            TaxAmount = taxAmount
        });
    }
}

IndividualTaxCalculator/IndividualTaxCalculator.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-3">Welcome</h1>
    <h1 class="display-6 mb-5">Please select an action below</h1>

    @Html.ActionLink("Calculate Individual Tax", "Index", "TaxCalculation", null, htmlAttributes: new { @class = "btn btn-primary" })
</div>

IndividualTaxCalculator/IndividualTaxCalculator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        2023 - Jared Benade
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

IndividualTaxCalculator/IndividualTaxCalculator.Web/Views/TaxCalculation/Index.cshtml
@model TaxCalculationRequestViewModel
@{
    ViewData["Title"] = "Calculate Tax";
}

<div>
    <h2>Calculate Individual Tax</h2>
    @using (Html.BeginForm())
    {
        <div class="mb-2">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "form-label" })
            @Html.DropDownListFor(model => model.PostalCode, new SelectList(Model.PostalCodes, "Value", "Text"), htmlAttributes: new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.PostalCode)
        </div>
        <div class="mb-2">
            @Html.LabelFor(model => model.AnnualIncome, htmlAttributes: new { @class = "form-label" })
            @Html.TextBoxFor(model => model.AnnualIncome, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AnnualIncome)
        </div>
        <input type="submit" value="Submit" class="btn btn-primary"/>
    }
</div>

IndividualTaxCalculator/IndividualTaxCalculator.Web/Views/TaxCalculation/Result.cshtml
@model TaxCalculationResultViewModel

@{
    ViewBag.Title = "Tax Calculation Result";
}

<div>
    <h2>@ViewBag.Title</h2>
    <div class="mb-2">
        @Html.LabelFor(model => model.TaxAmount, htmlAttributes: new { @class = "form-label" })
        @Html.TextBoxFor(model => model.TaxAmount, new { @readonly = "readonly", @class = "form-control" })
    </div>
    <div class="mb-2">
        @Html.LabelFor(model => model.AnnualIncome, htmlAttributes: new { @class = "form-label" })
        @Html.TextBoxFor(model => model.AnnualIncome, new { @readonly = "readonly", @class = "form-control" })
    </div>
    <div class="mb-2">
        @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "form-label" })
        @Html.TextBoxFor(model => model.PostalCode, new { @readonly = "readonly", @class = "form-control" })
    </div>

    @Html.ActionLink("Calculate Tax Again", "Index", "TaxCalculation", null, htmlAttributes: new { @class = "btn btn-primary" })
</div>